### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by twmills** [Pindar/alexa-template#2]
Any interest in adding nvm as a dependency? Since Lambda is locked to an older version of node, including an `.nvmrc` file locked to `6.10.3` might be helpful, as well as instructions on installing it.

https://github.com/creationix/nvm

Also, thanks for responding! This template has been a great kick starter.

**Comment by twmills** [comment]
Nevermind. Tried it and the older node doesn't play well with the tooling it seems.

**Comment by Pindar** [comment]
Thx for your contribution and your nice words. I'm happy this template helps!
